handlers:
    - id: content
      type: content
      patterns:
          - "*.md"
          - "*.json"

    - id: md
      type: markdown
      patterns: ["*.md"]
      prefix: "md"

    - id: custom
      type: custom
      bin: "{{ .AtlasPath }}/handlers/custom.js"
      patterns: ["*.md"]

actions:
    - id: vi
      type: shell
      command: tmux popup -E -h 90% -w 90% -x C -y C "vi {{ .EntryAbsolutePath }}"

    - id: generate-tasks
      type: shell
      command: "{{ .AtlasPath }}/bin/tasks.js 100"

keymaps:
    - keys: [g]
      action: generate-tasks
      description: Generate tasks
      groups: [global]

    - keys: [o]
      action: vi
      description: Open
      groups: [ext=md, ext=json]
