scan:
    exclude:
        - "package.json"
        - "README.md"
    include:
        - "tasks/*.md"
handlers:
    # - id: content
    #   type: content
    #   patterns:
    #       - "*.md"
    #       - "*.json"

    - id: md
      type: markdown
      patterns: ["**/*.md"]
      prefix: ""

    - id: json
      type: json
      patterns: ["**/*.json"]
      prefix: "json"

    # - id: custom
    #   type: custom
    #   bin: "{{ .AtlasPath }}/handlers/custom.js"
    #   patterns: ["*.md"]

actions:
    - id: vi
      type: shell
      command: tmux popup -E -h 90% -w 90% -x C -y C "vi {{ .EntryAbsolutePath }}"

    - id: generate-tasks
      type: shell
      command: "{{ .AtlasPath }}/bin/tasks.js 100"

keymaps:
    - keys: [g]
      action: generate-tasks
      description: Generate tasks
      groups: [global]

    - keys: [o]
      action: vi
      description: open
      groups: [ext=md, ext=json]

screens:
    - id: task_table
      type: entry_table
      title: "Tasks"
      query: "parent=tasks"
      description: "List of tasks"

    - id: task_detail
      type: custom
      title: "{{ .metas.title }}"
      components:
          - type: meta_box
            x: 0
            y: 0
            rows: 1
            cols: 1
            content: "{{ .metas.content }}"
