type: custom
title: "{{ .entry.title }}"
components:
    - type: text
      content: "{{ .entry.content }}"
      cols: 220
      rows: 37

    - type: form
      x: 220
      cols: 50
      rows: 37
      values: "={{ .entry }}"
      on_submit: "={{ .entry.update }}"
      fields:
          - id: title
            label: "Title"
            name: title

          - id: status
            label: "Status"
            name: status

          - id: priority
            label: "Priority"
            name: priority

          - id: project
            label: "Project"
            name: project

          - id: context
            label: "Context"
            name: context

          - id: favorite
            label: "Favorite"
            name: favorite

          - id: archived
            label: "Archived"
            name: archived

          - id: estimateHours
            label: "Estimate Hours"
            name: estimateHours

          - id: progress
            label: "Progress"
            name: progress

          # - id: tags
          #   label: "Tags"
          #   name: tags

          - id: created
            label: "Created"
            name: created

          - id: updated
            label: "Updated"
            name: updated

          # - id: due
          #   label: "Due Date"
          #   name: due
          #
          # - id: completed
          #   label: "Completed"
          #   name: completed
          #
          # - id: assignee
          #   label: "Assignee"
          #   name: assignee
          #
          # - id: reviewer
          #   label: "Reviewer"
          #   name: reviewer
