bindings:
    - keys: [a]
      action: input
      action_options:
          label: "Task name"
          submit: create-task
      description: create task
      groups: [global]

    - keys: [v]
      action: vi
      description: vim
      groups:
          - ext=md
          - ext=json

    - keys: [t]
      action: hello
      description: toast
      groups:
          - global

    - keys: [S]
      action: set-status
      description: update status
      groups:
          - parent=tasks
