type: entry_list
title: "tasks"
description: "List of tasks"
query: "parent=tasks"
# label_key: path
label_template: '󰂔 #{{ color .task_id "primary" }} {{ .title }} ({{ color_map .status .vars.status_colors }})'
component:
    type: "shell"
    command: |
      script -q /dev/null -c "glow -s {{ .workspace.atlas_path }}/glow-style.json {{ .entry.absolute_path }}" |
      sed '1{/^[[:space:]]*$/d}; ${/^[[:space:]]*$/d;}'
